name:  Deploy to GCP VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        IMAGE_URI=us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/my-repo/flask-app:latest
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: SSH and deploy container on VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_EXT_IP }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          sudo docker pulll us-central-docker.pkg.dev/${{ secrets.PROJECT_ID }}/my-repo/flask-app:latest
          sudo docker stop  flask-app || true
          sudo docker rm flask-app || true
          sudo docker run -d --name flask-app -p 80:80 us-central-docker.pkg.dev/${{ secrets.PROJECT_ID }}/my-repo/flask-app:latest
